{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "deployment-chart.fullname" . }}
  labels:
    {{- include "deployment-chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.autoscaling.targetKind }}
    name: {{ include "deployment-chart.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if or .Values.autoscaling.targetCPUUtilizationPercentage .Values.autoscaling.targetCPUAverageValue }}
    - type: Resource
      resource:
        name: cpu
        target:
        {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
            type: Utilization
            averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
        {{- end }}
        {{- if .Values.autoscaling.targetCPUAverageValue }}
            type: AverageValue
            averageValue: {{ .Values.autoscaling.targetCPUAverageValue }}
        {{- end }}
    {{- end }}
    {{- if or .Values.autoscaling.targetMemoryUtilizationPercentage .Values.autoscaling.targetMemoryAverageValue }}
    - type: Resource
      resource:
        name: memory
        target:
        {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
            type: Utilization
            averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
        {{- end }}
        {{- if .Values.autoscaling.targetMemoryAverageValue }}
            type: AverageValue
            averageValue: {{ .Values.autoscaling.targetMemoryAverageValue }}
        {{- end }}
    {{- end }}
{{- end }}
