apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  template:
    metadata:
      annotations:
      {{- if .Values.containerMaxScale }}
        autoscaling.knative.dev/maxScale: '{{ .Values.containerMaxScale }}'
      {{- end }}
      {{- if .Values.containerMinScale }}
        autoscaling.knative.dev/minScale: '{{ .Values.containerMinScale }}'
      {{- end }}
      {{- if .Values.vpcConnector.enabled }}
        run.googleapis.com/vpc-access-connector: {{ .Values.vpcConnector.name }}
      {{- end }}
      {{- if .Values.vpcAccessEgress.enabled }}
        run.googleapis.com/vpc-access-egress: {{ .Values.vpcAccessEgress.type }}
      {{- end }}
    spec:
    {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
    {{- end }}
    {{- if .Values.containerConcurrency }}
      containerConcurrency: {{ .Values.containerConcurrency }}
    {{- else }}
      containerConcurrency: 80
    {{- end }}
    {{- if .Values.timeoutSeconds }}
      timeoutSeconds: {{ .Values.timeoutSeconds }}
    {{- else }}
      timeoutSeconds: 300
    {{- end }}
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        {{- range $key, $value := .Values.envVars }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
